version: '3.8'
services:
  trackcombot:
    build:
      context: .
    container_name: trackcombot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo
    stdin_open: true
    tty: true
  mongo:
    container_name: mongo
    image: mongo:jammy
    restart: unless-stopped
    ports:
      - 3306:27017
    volumes:
      - 'trackcombot-mongo_db:/data/db'
      - 'trackcombot-mongo_configdb:/data/configdb'
volumes:
  trackcombot-mongo_db:
    name: 'trackcombot-mongo_db'
  trackcombot-mongo_configdb:
    name: 'trackcombot-mongo_configdb'
