version: '3.8'
services:
  trackcombot:
    image: ghcr.io/relitrix/commrad:latest
    restart: always
    env_file:
      - .env.production
    depends_on:
      - mongo
    stdin_open: true
    tty: true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  mongo:
    container_name: mongo
    image: mongo:7-jammy
    restart: always
    ports:
    - 3306:27017
    volumes:
      - 'trackcombot-mongo_db:/data/db'
      - 'trackcombot-mongo_configdb:/data/configdb'
  watchtower:
    image: containrrr/watchtower
    command: --debug --http-api-update
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/.docker/config.json:/config.json
    env_file:
      - .env.production
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8075:8080
volumes:
  trackcombot-mongo_db:
    name: 'trackcombot-mongo_db'
  trackcombot-mongo_configdb:
    name: 'trackcombot-mongo_configdb'
