version: '3.8'
services:
  trackcombot:
    build:
      context: .
    container_name: trackcombot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:jammy
    restart: unless-stopped
    ports:
      - 3306:27017
    volumes:
      - 'mongo_db:/data/db'
      - 'mongo_configdb:/data/configdb'
volumes:
  mongo_db:
    name: 'mongo_db'
  mongo_configdb:
    name: 'mongo_configdb'
